export const FETCH_ARTICLES_REQUEST = "FETCH_ARTICLES_REQUEST";
export const FETCH_ARTICLES_SUCCESS = "FETCH_ARTICLES_SUCCESS";
export const FETCH_ARTICLES_FAILURE = "FETCH_ARTICLES_FAILURE";

export const FETCH_ARTICLEBYID_REQUEST = "FETCH_ARTICLEBYID_REQUEST";
export const FETCH_ARTICLEBYID_SUCCESS = "FETCH_ARTICLEBYID_SUCCESS";
export const FETCH_ARTICLEBYID_FAILURE = "FETCH_ARTICLEBYID_FAILURE";

export const FETCH_ALL_TOPICS_REQUEST = "FETCH_ALL_TOPICS_REQUEST";
export const FETCH_ALL_TOPICS_SUCCESS = "FETCH_ALL_TOPICS_SUCCESS";
export const FETCH_ALL_TOPICS_FAILURE = "FETCH_ALL_TOPICS_FAILURE";
