export const FETCH_ARTICLES_REQUEST = "FETCH_ARTICLES_REQUEST";
export const FETCH_ARTICLES_SUCCESS = "FETCH_ARTICLES_SUCCESS";
export const FETCH_ARTICLES_FAILURE = "FETCH_ARTICLES_FAILURE";

export const FETCH_ARTICLEBYID_REQUEST = "FETCH_ARTICLEBYID_REQUEST";
export const FETCH_ARTICLEBYID_SUCCESS = "FETCH_ARTICLEBYID_SUCCESS";
export const FETCH_ARTICLEBYID_FAILURE = "FETCH_ARTICLEBYID_FAILURE";

export const FETCH_ALL_TOPICS_REQUEST = "FETCH_ALL_TOPICS_REQUEST";
export const FETCH_ALL_TOPICS_SUCCESS = "FETCH_ALL_TOPICS_SUCCESS";
export const FETCH_ALL_TOPICS_FAILURE = "FETCH_ALL_TOPICS_FAILURE";

export const FETCH_TOPIC_ARTICLES_REQUEST = "FETCH_TOPIC_ARTICLES_REQUEST";
export const FETCH_TOPIC_ARTICLES_SUCCESS = "FETCH_TOPIC_ARTICLES_SUCCESS";
export const FETCH_TOPIC_ARTICLES_FAILURE = "FETCH_TOPIC_ARTICLES_FAILURE";

export const FETCH_COMMENTS_REQUEST = "FETCH_COMMENTS_REQUEST";
export const FETCH_COMMENTS_SUCCESS = "FETCH_COMMENTS_SUCCESS";
export const FETCH_COMMENTS_FAILURE = "FETCH_COMMENTS_FAILURE";

export const POST_COMMENT_REQUEST = "POST_COMMENT_REQUEST";
export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS";
export const POST_COMMENT_FAILURE = "POST_COMMENT_FAILURE";

export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAILURE = "DELETE_COMMENT_FAILURE";
